[package]
name = "miri-repl-test"
version = "0.1.0"
authors = ["fschutt <felix.schuett@maps4print.com>"]
edition = "2018"

[dependencies]
miri = { git = "https://github.com/rust-lang/miri", rev = "96b22259cc0bacfeb7ca7fb9a370cf23e4649c36" }